### ISSUE TITLE
How do i use this?

### ISSUE THREAD

**Issue by yurividal** [datagutten/apc-smartconnect-py#1]
Hi. How do i use this? I am trying your sample.py, but i keep getting an error:

````
/apc-smartconnect-py$ python3 sample.py 'myusername' 'mypassword
Traceback (most recent call last):
  File "/home/sutadmin/apc-poller/apc-smartconnect-py/sample.py", line 8, in <module>
    smart = APCSmartConnect('cookies.lwp')
TypeError: APCSmartConnect.__init__() takes 1 positional argument but 2 were given
````

**Comment by datagutten** [comment]
I forgot to update sample.py after removing the class argument, I fixed it now and the script should be working.
Run it like `python sample.py [SmartConnect username] [SmartConnect password]`

The class should be pretty simple to use, call .login with username and password as arguments, then you can call .gateways to get a dict with information about all UPSs in your account.
The login will only be valid for a limited amount of time, then you have to login again.
I have not been able to make a new login from an existing class instance, so I have to delete the instance and create a new one.

**Comment by yurividal** [comment]
cool. it works now. I'm gonna play a bit with the outputs and see if i can manage to get it into influxdb for visualization with grafana. Hopefully i won't get blocked by apc for running this once every minute.

**Comment by datagutten** [comment]
I recommend that you keep an active session as long as it lasts and do not repeat the login process every minute.
I fear that they might add a captcha if we misuse it.
